### ISSUE TITLE
Crash on startup (NoAvailablePixelFormat)

### ISSUE THREAD

**Issue by vitvakatu** [three-rs/three#104]
Backtrace: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:92
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  11: gfx_window_glutin::init_raw
             at /home/fumlead/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.17.0/src/lib.rs:126
  12: gfx_window_glutin::init
             at /home/fumlead/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.17.0/src/lib.rs:58
  13: three::render::Renderer::new
             at src/render.rs:318
  14: three::window::Builder::build
             at src/window.rs:87
  15: materials::main
             at examples/materials.rs:6
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  18: main
  19: __libc_start_main
  20: _start
```
It happens with every example in current master.

Possible related to my system update:
```
[2017-09-12 18:18] [PACMAN] Running 'pacman --color auto -S -u'
[2017-09-12 18:18] [PACMAN] starting full system upgrade
[2017-09-12 18:22] [ALPM] running '70-dkms-remove.hook'...
[2017-09-12 18:22] [ALPM-SCRIPTLET] ==> dkms remove broadcom-wl/6.30.223.271 -k 4.12.10-1-ARCH
[2017-09-12 18:22] [ALPM] transaction started
[2017-09-12 18:22] [ALPM] upgraded linux-api-headers (4.10.1-1 -> 4.12.7-1)
[2017-09-12 18:22] [ALPM] warning: /etc/locale.gen installed as /etc/locale.gen.pacnew
[2017-09-12 18:22] [ALPM] upgraded glibc (2.25-7 -> 2.26-3)
[2017-09-12 18:22] [ALPM-SCRIPTLET] Generating locales...
[2017-09-12 18:22] [ALPM-SCRIPTLET]   en_US.UTF-8... done
[2017-09-12 18:22] [ALPM-SCRIPTLET] Generation complete.
[2017-09-12 18:22] [ALPM] upgraded binutils (2.28.0-4 -> 2.29.0-1)
[2017-09-12 18:22] [ALPM] upgraded gcc-libs (7.1.1-4 -> 7.2.0-2)
[2017-09-12 18:22] [ALPM] upgraded ncurses (6.0+20170527-1 -> 6.0+20170902-1)
[2017-09-12 18:22] [ALPM] upgraded btrfs-progs (4.12.1-1 -> 4.13-1)
[2017-09-12 18:22] [ALPM] upgraded coreutils (8.27-1 -> 8.28-1)
[2017-09-12 18:22] [ALPM] upgraded expat (2.2.3-1 -> 2.2.4-1)
[2017-09-12 18:22] [ALPM] upgraded fakeroot (1.21-2 -> 1.22-1)
[2017-09-12 18:22] [ALPM] upgraded harfbuzz (1.5.0-1 -> 1.5.1-1)
[2017-09-12 18:22] [ALPM] upgraded fontconfig (2.12.4-1 -> 2.12.5-1)
[2017-09-12 18:23] [ALPM-SCRIPTLET] Rebuilding fontconfig cache... done.
[2017-09-12 18:23] [ALPM] upgraded gcc (7.1.1-4 -> 7.2.0-2)
[2017-09-12 18:23] [ALPM] upgraded gpm (1.20.7-7 -> 1.20.7-8)
[2017-09-12 18:23] [ALPM] upgraded gsm (1.0.16-1 -> 1.0.17-1)
[2017-09-12 18:23] [ALPM] upgraded gtk-update-icon-cache (3.22.19-2 -> 3.22.20-1)
[2017-09-12 18:23] [ALPM] upgraded libinput (1.8.1-1 -> 1.8.2-1)
[2017-09-12 18:23] [ALPM] warning: /etc/drirc installed as /etc/drirc.pacnew
[2017-09-12 18:23] [ALPM] upgraded mesa (17.1.8-2 -> 17.2.0-2)
[2017-09-12 18:23] [ALPM] upgraded gtk3 (3.22.19-2 -> 3.22.20-1)
[2017-09-12 18:23] [ALPM] upgraded lib32-glibc (2.25-7 -> 2.26-2)
[2017-09-12 18:23] [ALPM] upgraded lib32-gcc-libs (7.1.1-4 -> 7.2.0-1)
[2017-09-12 18:23] [ALPM] upgraded lib32-libelf (0.169-1 -> 0.169-2)
[2017-09-12 18:23] [ALPM] upgraded lib32-libxau (1.0.8-1 -> 1.0.8-2)
[2017-09-12 18:23] [ALPM] upgraded lib32-ncurses (6.0+20170527-1 -> 6.0+20170527-2)
[2017-09-12 18:23] [ALPM] upgraded lib32-mesa (17.1.8-2 -> 17.2.0-1)
[2017-09-12 18:23] [ALPM] upgraded libtool (2.4.6-8 -> 2.4.6+40+g6ca5e224-1)
[2017-09-12 18:23] [ALPM] upgraded libxslt (1.1.29+42+gac341cbd-1 -> 1.1.30-1)
[2017-09-12 18:23] [ALPM] upgraded mkinitcpio (23-1 -> 23-2)
[2017-09-12 18:23] [ALPM] upgraded linux (4.12.10-1 -> 4.12.12-1)
[2017-09-12 18:23] [ALPM-SCRIPTLET] >>> Updating module dependencies. Please wait ...
[2017-09-12 18:23] [ALPM] upgraded linux-headers (4.12.10-1 -> 4.12.12-1)
[2017-09-12 18:24] [ALPM] upgraded vim-runtime (8.0.1066-1 -> 8.0.1092-1)
[2017-09-12 18:24] [ALPM] upgraded vim (8.0.1066-1 -> 8.0.1092-1)
[2017-09-12 18:24] [ALPM] transaction completed
```

I'm investigating it now.

**Comment by vitvakatu** [comment]
UPD: gfx and glutin examples work fine

**Comment by vitvakatu** [comment]
I reverted system upgrade and it works now. Leaving this issue for futher investigation. (I need to update someday, huh?)

**Comment by kvark** [comment]
@vitvakatu please investigate when you get a chance

**Comment by alteous** [comment]
> need to play with our glutin context builder options to find out why it doesn't like them

To confirm, I'm using Kubuntu and the context builder options are completely ignored.

The window always appears full sized, but not fullscreen, regardless of specified window size and fullscreen option. The title is OK though.

**Comment by vitvakatu** [comment]
Relative issue in `Amethyst` project: https://github.com/amethyst/amethyst/issues/344

**Comment by vitvakatu** [comment]
UPD: have information about the same bug on Ubuntu 17.04, GPU Intel HD Graphics 5500

**Comment by jojolepro** [comment]
I got the error NoAvailablePixelFormat when trying to run it in a windows virtual machine.
I got a stackoverflow when resizing on my intel cpu under windows 7.
Works fine on windows 7 + nvidia gpu
Works fine on ubuntu + nvidia gpu.

The errors I got are probably not related, as other people have confirmed it to work just fine.

**Comment by XX** [comment]
In my case, the problem occurred in the glutin crate, on this line:
```
let configs = glx.ChooseFBConfig(display as *mut _, screen_id, descriptor.as_ptr(),
                                &mut num_configs);
```
(https://github.com/tomaka/glutin/blob/master/src/api/glx/mod.rs#L492)
`glx.ChooseFBConfig` returned a zero value if the descriptor had sRGBA enabled. By default, three-rs use sRGBA color format:
```
pub type ColorFormat = gfx::format::Srgba8;
```
(https://github.com/three-rs/three/blob/master/src/render.rs#L31)
When I change it to Rgba8 color format, three-rs examples work fine.

**Comment by vitvakatu** [comment]
Now I can confirm, changing `ColorFormat` to `Rgba8` fixed issue for me.
