### ISSUE TITLE
'tutorial' example panics on MacOS

### ISSUE THREAD

**Issue by spacejack** [three-rs/three#178]
Tested on MacOS Sierra, Mac Mini (late 2014)

Backtrace output:

```
     Running `target/debug/examples/tutorial`
thread 'main' panicked at 'gl function was not loaded', /Users/link/Documents/three/target/debug/build/gfx_gl-ebf030e2cd4f2fb4/out/gl_bindings.rs:1506:12
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:538
   6: gfx_gl::missing_fn_panic
             at ./target/debug/build/gfx_gl-ebf030e2cd4f2fb4/out/gl_bindings.rs:1506
   7: gfx_gl::Gl::DrawArraysInstancedBaseInstance
             at ./target/debug/build/gfx_gl-ebf030e2cd4f2fb4/out/gl_bindings.rs:3573
   8: gfx_device_gl::Device::process
             at /Users/link/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.0/src/lib.rs:667
   9: gfx_device_gl::Device::no_fence_submit
             at /Users/link/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.0/src/lib.rs:815
  10: gfx_device_gl::Device::track_mapped_gpu_access
             at /Users/link/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.0/src/lib.rs:937
  11: <gfx::encoder::Encoder<R, C>>::flush_no_reset
             at /Users/link/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:197
  12: <gfx::encoder::Encoder<R, C>>::flush
             at /Users/link/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:188
  13: three::render::Renderer::map_to_ndc
             at src/render/mod.rs:975
  14: three::window::Window::update::{{closure}}
             at src/window.rs:235
  15: tutorial::main
             at examples/tutorial.rs:26
  16: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101
  17: rust_panic
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:365
             at src/libstd/rt.rs:58
  18: tutorial::main
```

**Comment by THeK3nger** [comment]
I can replicate this error. It is related to [this bug](https://github.com/gfx-rs/gfx/issues/1298) on GFX

**Comment by kvark** [comment]
Thanks for reporting and tracking this down!
